#define PORT_DEFAULT "58033"
#define MAX_PORT_SIZE 6
#define MAX_INPUT_SIZE 280
#define MAX_OUTPUT_SIZE 3600
#define MAX_UID_SIZE 6
#define MAX_PASS_SIZE 9
#define MAX_GID_SIZE 3
#define MAX_GNAME_SIZE 25
#define MAX_MID_SIZE 5
#define MAX_OPTYPE_SIZE 11

