int validUID(char *input);
int validPassword(char *input);
int validGID(char *input);
int validGName(char *input);
void registerUser(char *input);
void unregisterUser(char *input);
void loginUser(char *input);
void logoutUser();
void exitSession();
void listUsers_GID();
void showAvailableGroups();
void subscribeGroup(char *input);
void unsubscribeGroup(char *input);
void showMyGroups();
void selectGroup(char *input);
void showGIDSelected();
void listUsers_GID();
void initSession(char *hostName, char *port);
void exitSession();
/* headers das funcoes/operacoes do user */